# 🎊 Learning PyTorch at `My Pace` 🤗

## Know Your System and Install

In [27]:
!lscpu |grep 'Model name'
!lsmem |grep 'Total'

Model name:                         Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Total online memory:       4G
Total offline memory:      0B


In [28]:
!nvidia-smi ## May or May not have your GPU lol

/bin/bash: line 1: nvidia-smi: command not found


Install PyTorch if not yet

In [21]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.4/195.4 MB 3.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 16.4 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 30.2 MB/s eta 0:00:00:00:01


## Time to Play, with `Tensor`s 🃏

In [22]:
import torch
import numpy as np

### Convert `things` to tensors AT YOUR WILL

**You can do normal `np.array`s**

In [32]:
data_array = np.array([[1, 2],[3, 4]])
print(data_array.dtype)
print(data_array.shape)
print(type(data_array))

int64
(2, 2)
<class 'numpy.ndarray'>


In [33]:
data_array_t = torch.tensor(data_array)
print(data_array_t.dtype)
print(data_array_t.shape)
print(type(data_array_t))

torch.int64
torch.Size([2, 2])
<class 'torch.Tensor'>


**Can do like a `list`**

In [31]:
data_list = [[ 1, 2 ],
             [3, 4],]
print(len(data_list))
print(type(data_list))

2
<class 'list'>


In [34]:
data_list_t = torch.tensor(data_list)
print(data_list_t.dtype)
print(data_list_t.shape)
print(type(data_list_t))

torch.int64
torch.Size([2, 2])
<class 'torch.Tensor'>


**Can do other `tensor`s**
Notes:
- When you use `torch.ones_like` or `torch.rand_like`, only put in a `Tensor`

In [39]:
ones_t = torch.ones_like(data_array_t) 
ones_t

tensor([[1, 1],
        [1, 1]])

In [46]:
rand_t = torch.rand_like(data_array_t, dtype = torch.float64)  #! dtype only takes `torch.dtype`
rand_t

tensor([[0.8358, 0.1689],
        [0.6136, 0.6609]], dtype=torch.float64)

In [52]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: shape {rand_tensor.shape} \n {rand_tensor} \n")
print(f"Ones Tensor: shape {rand_tensor.shape} \n {ones_tensor} \n")
print(f"Zeros Tensor: shape {rand_tensor.shape} \n {zeros_tensor}")

Random Tensor: shape torch.Size([2, 3]) 
 tensor([[0.0384, 0.7548, 0.5116],
        [0.9969, 0.0640, 0.0423]]) 

Ones Tensor: shape torch.Size([2, 3]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: shape torch.Size([2, 3]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Operations on `Tensors`

***Inspect a `Tensor`***

In [59]:
tensor = torch.rand((3,4,2), dtype = torch.float64)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4, 2])
Datatype of tensor: torch.float64
Device tensor is stored on: cpu


In [61]:
if torch.cuda.is_available():
    print("cuda is available")
    tensor = tensor.to("cuda")

In [70]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,2] = 4
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 4., 1.],
        [1., 1., 4., 1.],
        [1., 1., 4., 1.],
        [1., 1., 4., 1.]])


In [71]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 1., 4., 1., 1., 1., 4., 1., 1., 1., 4., 1.],
        [1., 1., 4., 1., 1., 1., 4., 1., 1., 1., 4., 1.],
        [1., 1., 4., 1., 1., 1., 4., 1., 1., 1., 4., 1.],
        [1., 1., 4., 1., 1., 1., 4., 1., 1., 1., 4., 1.]])


In [72]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

In [73]:
y1

tensor([[19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.]])

In [74]:
y2

tensor([[19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.]])

In [78]:
y3 = torch.ones_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.]])

In [80]:
z1= tensor * tensor
z1

tensor([[ 1.,  1., 16.,  1.],
        [ 1.,  1., 16.,  1.],
        [ 1.,  1., 16.,  1.],
        [ 1.,  1., 16.,  1.]])

In [81]:
agg = tensor.sum()

In [82]:
agg

tensor(28.)

## Automatic Differentiation w/ `torch.autograd`

## RUN `FOOOCUS`

In [ ]:
%cd /content
!git clone -b v1.0.43 https://github.com/camenduru/Fooocus

!apt -y update -qq
!wget https://github.com/camenduru/gperftools/releases/download/v1.0/libtcmalloc_minimal.so.4 -O /content/libtcmalloc_minimal.so.4
%env LD_PRELOAD=/content/libtcmalloc_minimal.so.4

!pip install torchsde==0.2.5 einops==0.4.1 transformers==4.30.2 safetensors==0.3.1 accelerate==0.21.0
!pip install pytorch_lightning==1.9.4 omegaconf==2.2.3 gradio==3.39.0 xformers==0.0.20 triton==2.0.0 pygit2==1.12.2

!apt -y install -qq aria2
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/ckpt/juggernaut-xl/resolve/main/juggernautXL_version1.safetensors -d /content/Fooocus/models/checkpoints -o juggernautXL_version1.safetensors
# !aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/ckpt/juggernaut-xl/resolve/main/sdxl_vae.safetensors -d /content/Fooocus/models/vea -o sdxl_vae.safetensors
# !aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/ckpt/juggernaut-xl/resolve/main/JuggerCineXL2.safetensors -d /content/Fooocus/models/loras -o JuggerCineXL2.safetensors

%cd /content/Fooocus
!git pull
!python launch.py --share